# NUMPY

In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3])

In [4]:
a.ndim

1

In [8]:
b=np.array([[1,2],[2,3],[3,4]])

In [9]:
b

array([[1, 2],
       [2, 3],
       [3, 4]])

In [10]:
b.itemsize

4

In [11]:
a.itemsize

4

In [15]:
a=np.array([1,2,3],dtype=np.uint)

In [16]:
a

array([1, 2, 3], dtype=uint32)

In [17]:
a.itemsize

4

In [19]:
a=np.array([1,2,3],dtype=np.float64)

In [21]:
a.itemsize

8

In [22]:
b=np.array([[1,2],[2,3],[3,4]],dtype=np.float64)

In [23]:
b

array([[1., 2.],
       [2., 3.],
       [3., 4.]])

In [24]:
b.itemsize

8

In [25]:
b.dtype

dtype('float64')

In [26]:
b.size

6

In [27]:
a.size

3

In [28]:
a=np.array([1,2,3],dtype=complex)

In [29]:
a

array([1.+0.j, 2.+0.j, 3.+0.j])

In [30]:
np.zeros(a.itemsize)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
b.ravel()

array([1., 2., 2., 3., 3., 4.])

In [35]:
np.array(b.ravel(),dtype=np.int32)

array([1, 2, 2, 3, 3, 4])

In [36]:
b.min()

1.0

In [37]:
b.max()

4.0

In [40]:
s=b.reshape(2,3)

In [41]:
s.sum(axis=0)

array([4., 5., 6.])

In [42]:
s

array([[1., 2., 2.],
       [3., 3., 4.]])

In [43]:
s.sum(axis=1)

array([ 5., 10.])

In [45]:
t=np.square(s)
print(t)

[[ 1.  4.  4.]
 [ 9.  9. 16.]]


In [46]:
np.sqrt(t)

array([[1., 2., 2.],
       [3., 3., 4.]])